// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: Previrt.proto

#include "Previrt.pb.h"
#include "Previrt.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace previrt {
namespace proto {

static const char* QueryOracle_method_names[] = {
  "/previrt.proto.QueryOracle/Query",
};

std::unique_ptr< QueryOracle::Stub> QueryOracle::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< QueryOracle::Stub> stub(new QueryOracle::Stub(channel));
  return stub;
}

QueryOracle::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_Query_(QueryOracle_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status QueryOracle::Stub::Query(::grpc::ClientContext* context, const ::previrt::proto::State& request, ::previrt::proto::Prediction* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_Query_, context, request, response);
}

void QueryOracle::Stub::experimental_async::Query(::grpc::ClientContext* context, const ::previrt::proto::State* request, ::previrt::proto::Prediction* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_Query_, context, request, response, std::move(f));
}

void QueryOracle::Stub::experimental_async::Query(::grpc::ClientContext* context, const ::previrt::proto::State* request, ::previrt::proto::Prediction* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_Query_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::previrt::proto::Prediction>* QueryOracle::Stub::PrepareAsyncQueryRaw(::grpc::ClientContext* context, const ::previrt::proto::State& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::previrt::proto::Prediction>::Create(channel_.get(), cq, rpcmethod_Query_, context, request, false);
}

::grpc::ClientAsyncResponseReader< ::previrt::proto::Prediction>* QueryOracle::Stub::AsyncQueryRaw(::grpc::ClientContext* context, const ::previrt::proto::State& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncQueryRaw(context, request, cq);
  result->StartCall();
  return result;
}

QueryOracle::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      QueryOracle_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< QueryOracle::Service, ::previrt::proto::State, ::previrt::proto::Prediction>(
          [](QueryOracle::Service* service,
             ::grpc::ServerContext* ctx,
             const ::previrt::proto::State* req,
             ::previrt::proto::Prediction* resp) {
               return service->Query(ctx, req, resp);
             }, this)));
}

QueryOracle::Service::~Service() {
}

::grpc::Status QueryOracle::Service::Query(::grpc::ServerContext* context, const ::previrt::proto::State* request, ::previrt::proto::Prediction* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace previrt
}  // namespace proto

